# Generated by Django 3.0.2 on 2020-01-03 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200103_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folders',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
